### ISSUE TITLE
Update the language folder

### ISSUE THREAD

**Issue by mathetos** [mathetos/export-users-to-csv#1]
The language folder is currently inside the plugin. We need to move it to the uploads folder so no localized translations are lost on plugin update.

**Comment by tormjens** [comment]
Actually. I think WordPress looks for a language file in the `wp-content/languages/plugin-name/plugin-name-xx_XX.mo` when you use the `load_plugin_textdomain` function. So no need to move the ones in the plugin already out of the plugin. Users can simply upload their own language files to the mentioned folder.

**Comment by mathetos** [comment]
That's correct -- not the uploads folder as I mentioned. But I believe the plugin needs to be updated to look for the langauge files there.

You can refer to how we do it in the Give plugin:
https://github.com/WordImpress/Give/blob/release/1.8.14/give.php#L504-L518
