### ISSUE TITLE
Research potential for filtering exports by user meta

### ISSUE THREAD

**Issue by loretoparisi** [mathetos/export-users-to-csv#10]
In my web site I'm managing customers with multiple roles and User Groups - managed by [User Access Manager](https://wordpress.org/plugins/user-access-manager/) plugin, that belong to one or more user groups e.g. a certain customer that has a specific role can be in more than one group.
So farI can export only users by "role" and "date", therefore I will miss the User Groups concept, then my export will lack important data i.e. the one to many association between a user and the groups who belongs to.
Any way then to export users by both their group and the role affiliation?

**Comment by mathetos** [comment]
I like the idea for sure. It will take some research to understand how User Access Manager creates those groups. Are they user meta? If so, I can look into supporting user meta as a filter option in doing the export. Otherwise, if they've concoted some unorthodox method of creating these groups then it's not likely at all.

It's important to me that this plugin stay focused on its core purpose and do things the WordPress way. Compatibility will all kinds of other user-related plugins isn't a priority. But allowing the exports to be filtered by user meta is a fascinating idea which I promise to explore. Thanks!

**Comment by loretoparisi** [comment]
@mathetos thanks, it makes a lot of sense to keep things compatible for all users and working in the standard way. I will take a closer look at the way how UAM handles the users in the database.

**Comment by loretoparisi** [comment]
So in my finding it seems to me that *UAM* it is not using the `wp_usermeta` table to add properties to the user.
They have at least two tables, one that defines the access groups, and one that is mapping each group to the users in a one to many relation, since a user belongs to one or more groups.
The *UAM* plugin has a public API to access its context and users from external plugins like:

```php
global $userAccessManager;

if (isset($userAccessManager)) {
    $userGroupHandler = $userAccessManager->getUserGroupHandler();
    $userGroupsForUser = $userGroupHandler->getUserGroupsForObject(
        \UserAccessManager\Object\ObjectHandler::GENERAL_USER_OBJECT_TYPE,
        $userId
    );
    //Given that you already have the user group.
    $usersInGroup = $userGroupsForUser->getFullUsers();
}
```

I have asked the UAM author about this API as well https://github.com/GM-Alex/user-access-manager/issues/220

Thanks a lot for your help, both yours and uam plugin are very useful, and it would make a lot of sense to support / extend the export of users capabilities for them in some "standard" as you say of course.

Thanks again, if I have more info I will post.

**Comment by mathetos** [comment]
Sounds good. If you have more info related to User Meta and exports, I'm closing this issue in favor of #4 since it's essentially a duplicate. Thanks!

**Comment by loretoparisi** [comment]
@mathetos thanks, If I have any updates or any news from the UAM author I will keep you posted.

**Comment by loretoparisi** [comment]
@mathetos I was finally able to do the export of UAM groups. As you stated it was not using the standard `wp_capabilities` but its own database, also those fields are not included as `usermeta`, but since I think this would be useful for many users, I would like to publish it as a plugin, but of course it is inspired and based on your plugin code, so I would like to know your opinion about that. Of course it would something that will keep the same license, disclaimer, reference, etc.

**Comment by mathetos** [comment]
Thanks for the update, and for asking @loretoparisi

I think there are two options here:
1) You can fork this plugin to create your own, as you stated, with proper attribution and whatnot
2) Or you can submit a Pull Request here, and I can add you as a contributor to this plugin.

I'm fine with either option.
