### ISSUE TITLE
User export for speciic months don't work

### ISSUE THREAD

**Issue by sbskamey** [mathetos/export-users-to-csv#12]
For example, I want to export User Data for February 2018 to February 2018. Instead, it exports the entire database of users. Using 4.9.4 Wordpress.

**Comment by mathetos** [comment]
Hmmm... thanks for reporting that. I'll take a closer look and let you know what I find.

**Comment by mathetos** [comment]
@sbskamey -- I just pushed version 1.1.1 to the .org plugin directory which fixes this issue. Thanks for reporting!

**Comment by sbskamey** [comment]
Great, thanks! :)
