### ISSUE TITLE
Move location to under "Tools > Export"

### ISSUE THREAD

**Issue by mathetos** [mathetos/export-users-to-csv#2]
The most native experience for this should be in the "Tools > Export" menu, not under "Users". Let's move it there and use as much of the native functions of that screen as we can.

**Comment by tormjens** [comment]
I'm on it. Did you think just moving it to the "Tools" tab, or moving the entire thing in to the same screen as "Export" ?

**Comment by mathetos** [comment]
Hi @tormjens thanks so much!

Yes, I'm thinking directly into the Export screen seamlessly, like this:
![image](https://user-images.githubusercontent.com/930724/31477411-ca529234-aec0-11e7-989f-4a1bfa474db3.png)

I believe what you need is the `export_filters` action: https://developer.wordpress.org/reference/hooks/export_filters/

But I noticed that doesn't put the input inside the `<fieldset>` of the other exports. Interested in what you come up with for sure.

Thanks! Happy #Hacktoberfest!
