### ISSUE TITLE
Fatal error when executed

### ISSUE THREAD

**Issue by bxdavi2** [mathetos/export-users-to-csv#9]
I clicked on export to csv and got the following error

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 64 bytes) in /hsphere/local/home/bbbn9gn/petroleumeducationworkshops.com/wp-includes/wp-db.php on line 2516

**Comment by mathetos** [comment]
Most likely your server resources aren't enough to export all the users you have. Please do the following:

1) Install this free plugin (also mine): "Send System Info"
2) Submit your Support request here: https://wordpress.org/support/plugin/export-users-to-csv/
3) In your support request, tell me how many users you have
4) In your support request, also provide me the System Info LINK that you create with the Send System Info plugin

Thanks!
